jasdja

diff --git a/s2i-test/.s2i/bin/assemble b/s2i-test/.s2i/bin/assemble
--- a/s2i-test/.s2i/bin/assemble
+++ b/s2i-test/.s2i/bin/assemble
@@ -1,41 +1,13 @@
 #!/bin/bash
+echo "Makingasdasd ETIENNE ASDLASLDLA SLDL ASLDL ASLDLSA LDASL DLSAL DLASLL DLSALD LAS pre-invocation changes..."
 
-set -e
+/usr/libexec/s2i/assemble
+rc=$?
 
-source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh
-
-echo "---> Enabling s2i support in httpd24 image AV MILLE AV MILLE AV MILLE AV MILLE AV MILLE AV MILLE"
-
-config_s2i
-
-######## CUSTOMIZATION STARTS HERE ############
-
-echo "---> Installing application source AV MILLE AV MILLE AV MILLE AV MILLE AV MILLE"
-cp -Rf /tmp/src/*.html ./etienne
-
-DATE=`date "+%b %d, %Y @ %H:%M %p"`
-
-echo "---> Creating info page AV MILLE AV MILLE AV MILLE AV MILLE AV MILLE AV MILLE AV MILLE"
-echo "Page built on $DATE" >> ./info.html
-echo "Proudly served by Apache HTTP Server version $HTTPD_VERSION" >> ./info.html
-
-######## CUSTOMIZATION ENDS HERE ############
-
-if [ -d ./httpd-cfg ]; then
-  echo "---> Copying httpd configuration files..."
-  if [ "$(ls -A ./httpd-cfg/*.conf)" ]; then
-    cp -v ./httpd-cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-    rm -rf ./httpd-cfg
-  fi
+if [ $rc -eq 0 ]; then
+    echo "Making post-invocation changes..."
 else
-  if [ -d ./cfg ]; then
-    echo "---> Copying httpd configuration files from deprecated './cfg' directory, use './httpd-cfg' instead..."
-    if [ "$(ls -A ./cfg/*.conf)" ]; then
-      cp -v ./cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-      rm -rf ./cfg
-    fi
-  fi
+    echo "Error: assemble failed!"
 fi
 
-# Fix source directory permissions
-fix-permissions ./
+exit $rc
